### ISSUE TITLE
Update to NET 9.0

### ISSUE THREAD

**Issue by sevinul** [ScarletKuro/Blazor.WebAssembly.DynamicCulture#4]
Hello ScarletKuro,
Do you plan to update this project  to NET 9.0?
Best regards

**Comment by ScarletKuro** [comment]
Hi.
Technically, the current version should work in .NET 9.0. I don't see any specific changes made by Microsoft in the [WebAssemblyCultureProvider](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs) that would require the library to explicitly target .NET 9. The compiled version against .NET 8 should be backward compatible with .NET 9.

**Comment by sevinul** [comment]
Thank you for responding. I migrated a sample project to NET 9.0: https://github.com/sevinul/Blazor_App_With_Auth/
It was working on NET 8.0. On NET 9.0 PR6 it fails on start with this message:

````
logging.ts:129 [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/object.c:2534

Error
    at Nc (https://localhost:44303/_framework/dotnet.runtime.9.0.0-preview.6.24327.7.ny1xcl4zfy.js:3:167619)
    at wasm://wasm/00b4b516:wasm-function[163]:0xae3d
    at wasm://wasm/00b4b516:wasm-function[654]:0x428b3
    at wasm://wasm/00b4b516:wasm-function[571]:0x40802
    at wasm://wasm/00b4b516:wasm-function[575]:0x40923
    at wasm://wasm/00b4b516:wasm-function[578]:0x4098c
    at wasm://wasm/00b4b516:wasm-function[2575]:0xc7e45
    at wasm://wasm/00b4b516:wasm-function[368]:0x2b152
    at wasm://wasm/00b4b516:wasm-function[357]:0x234d8
    at wasm://wasm/00b4b516:wasm-function[399]:0x2f29d
````

If I comment out lines 1, 2, 41-52, 56 in Blazor_App_With_Auth.Client/program.cs, the program starts ok without dynamic translation.

**Comment by ScarletKuro** [comment]
Ok, thanks for the info. I will later try on net9

**Comment by ScarletKuro** [comment]
Should be fixed in 3.1.0 version

**Comment by sevinul** [comment]
Perfect :)

**Comment by sevinul** [comment]
Perfect :) It works like a champ.
